// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLNM9M_qkRSnEBTaiCZzOOcANoRZ_v_8U',
    appId: '1:296204167686:web:bc116af15ef4437159f187',
    messagingSenderId: '296204167686',
    projectId: 'pesona-galuh',
    authDomain: 'pesona-galuh.firebaseapp.com',
    storageBucket: 'pesona-galuh.firebasestorage.app',
    measurementId: 'G-L2SXXQ9C58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTsd8CohnqI-tJkWc6nszi2EQs089GwvE',
    appId: '1:296204167686:android:c9e08ef5e55ea9a959f187',
    messagingSenderId: '296204167686',
    projectId: 'pesona-galuh',
    storageBucket: 'pesona-galuh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv-KWJSLvCIxljyqTnKaZE1r7IeKP9eks',
    appId: '1:296204167686:ios:13adada8a1ebb80359f187',
    messagingSenderId: '296204167686',
    projectId: 'pesona-galuh',
    storageBucket: 'pesona-galuh.firebasestorage.app',
    iosBundleId: 'com.example.pesonagaluh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv-KWJSLvCIxljyqTnKaZE1r7IeKP9eks',
    appId: '1:296204167686:ios:13adada8a1ebb80359f187',
    messagingSenderId: '296204167686',
    projectId: 'pesona-galuh',
    storageBucket: 'pesona-galuh.firebasestorage.app',
    iosBundleId: 'com.example.pesonagaluh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLNM9M_qkRSnEBTaiCZzOOcANoRZ_v_8U',
    appId: '1:296204167686:web:2f421711cb7ccf7959f187',
    messagingSenderId: '296204167686',
    projectId: 'pesona-galuh',
    authDomain: 'pesona-galuh.firebaseapp.com',
    storageBucket: 'pesona-galuh.firebasestorage.app',
    measurementId: 'G-XM76QRQK2E',
  );
}
